# Generated by Django 5.2.6 on 2025-12-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
