# Generated by Django 5.2.6 on 2025-10-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_image', models.ImageField(upload_to='products/')),
                ('product_name', models.CharField(max_length=255)),
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_details', models.CharField(max_length=500)),
            ],
        ),
    ]
