# Generated by Django 5.2.6 on 2025-10-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_product_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category_id',
            field=models.IntegerField(default=1),
        ),
    ]
