# Generated by Django 5.2.6 on 2025-10-16 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0003_products_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category_id',
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categories.categories'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_details',
            field=models.CharField(max_length=5000),
        ),
    ]
