# Generated by Django 5.2.6 on 2025-11-11 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_products_category_id_products_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
